name: Deploy Shuttle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Deploy Shuttle
        uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JFF66P53CMEK53RXFQEXM1C6
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            MONGODB_URI = '${{ secrets.MONGODB_URI }}'
            RIOT_API_KEY = '${{ secrets.RIOT_API_KEY }}'
            SUGGESTIONS_CHANNEL_ID = '${{ secrets.SUGGESTIONS_CHANNEL_ID }}'